# Generated by Django 3.1.7 on 2021-02-26 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson1', '0002_auto_20210226_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
