# Generated by Django 3.1.7 on 2021-02-26 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson1', '0003_auto_20210226_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
